<?php

namespace Sdz\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function findByAuteurDesc($auteur)
	{
		$qb = $this->createQueryBuilder('a');

		$qb->where('a.auteur = :auteur')
		   ->setParameter('auteur', $auteur)
		  ->orderBy('a.date', 'DESC');

		return $qb->getQuery()
				  ->getResult();
	}

	public function getArticleAvecCommentaires()
	{
	  $qb = $this->createQueryBuilder('a')
	             ->leftJoin('a.commentaires', 'c')
	             ->addSelect('c');
	 
	  return $qb->getQuery()
	            ->getResult();
	}

	public function getAvecCategories(array $nom_categories)
	{
		$qb = $this->createQueryBuilder('a');

		// On fait une jointure avec l'entité Categorie, avec pour alias « c »
		$qb ->join('a.categories', 'c')
		    ->where($qb->expr()->in('c.nom', $nom_categories)); // Puis on filtre sur le nom des catégories à l'aide d'un IN

		// Enfin, on retourne le résultat
		return $qb->getQuery()
		          ->getResult();
	}
}
